{
    "version": 4,
    "data": {
        "envValue": "env/env.env",
        "title": "3.1",
        "remarks": "",
        "testCode": "31",
        "config": {},
        "deviceList": [
            {
                "id": "GwoXPwxRxinUN6viz_9TZ",
                "name": "仿真设备(脚本)",
                "luaVal": "func/3interface_shoot.lua",
                "yamlVal": "testdata/data_biao3.yml",
                "kind": "SIMU"
            }
        ],
        "channelList": [
            {
                "id": "WHbw5R7tCSJU4u-XiLH6I",
                "name": "仿真设备(脚本)",
                "items": [
                    {
                        "name": "shoot",
                        "checked": true
                    },
                    {
                        "name": "target",
                        "checked": true
                    }
                ]
            },
            {
                "id": "gZog3YA6FX4vj8kb7zD1W",
                "name": "实物设备",
                "items": [
                    {
                        "name": "COM_shoot",
                        "checked": true
                    },
                    {
                        "name": "COM_target",
                        "checked": true
                    }
                ]
            }
        ],
        "protocolList": [
            {
                "name": "target",
                "uri": "prot/target.prot",
                "checked": true
            },
            {
                "name": "shoot",
                "uri": "prot/shoot.prot",
                "checked": true
            }
        ]
    }
}