{
    "version": 4,
    "data": {
        "envValue": "env/env.env",
        "title": "4.1",
        "remarks": "",
        "testCode": "41",
        "config": {},
        "deviceList": [
            {
                "id": "HSIEqGOfJvs21KV4lVteZ",
                "name": "仿真设备(脚本)",
                "luaVal": "func/4interface_target.lua",
                "yamlVal": "testdata/data_biao.yml",
                "kind": "SIMU"
            }
        ],
        "channelList": [
            {
                "id": "Bz0p7zOO9PCrSUN5WveLz",
                "name": "仿真设备(脚本)",
                "items": [
                    {
                        "name": "shoot",
                        "checked": true
                    },
                    {
                        "name": "target",
                        "checked": true
                    }
                ]
            },
            {
                "id": "BLll2fILO4gDzd2Vt_aj4",
                "name": "实物设备",
                "items": [
                    {
                        "name": "COM_shoot",
                        "checked": true
                    },
                    {
                        "name": "COM_target",
                        "checked": true
                    }
                ]
            }
        ],
        "protocolList": [
            {
                "name": "target",
                "uri": "prot/target.prot",
                "checked": true
            },
            {
                "name": "shoot",
                "uri": "prot/shoot.prot",
                "checked": true
            }
        ]
    }
}